### ISSUE TITLE
Error while adding package to ember-cli project

### ISSUE THREAD

**Issue by wolfbiter** [lightblade/ember-cli-d3#23]
Hi! I'm super impressed by this - I love ember and D3. I'm just getting started with a project that will make use of D3 (interactive bezier curves, dynamic axes... a music app, with beat grids and automation curves). I looked through your docs and examples - I'm excited to use your addon!

I was trying to install `ember-cli-d3` and got the following error:

![image](https://cloud.githubusercontent.com/assets/1360563/10270133/bfd999c4-6a9d-11e5-8a21-d180b3045f3e.png)

my project versions:

![image](https://cloud.githubusercontent.com/assets/1360563/10270150/108e97de-6a9e-11e5-9908-7a4e0e4c54f9.png)

i suspect this is just a missing lodash dependency - will try to add to my local and see if that resovles, then report back here

thank you for your awesome work!

**Comment by wolfbiter** [comment]
Yeah, fixed with `npm install lodash`. not sure if this is an unlisted dep in your proj or mine...

**Comment by ming-codes** [comment]
Thanks for filing the bug! I see the problem is caused by including lodash as `devDependencies` and not `dependencies`. It'll be a quick fix.

**Comment by ming-codes** [comment]
Fixed and published as v0.7.1
