### ISSUE TITLE
dummy app not running

### ISSUE THREAD

**Issue by ffaerber** [lightblade/ember-cli-d3#27]
after cloning bower i, npm i and ember s
on http://localhost:4200/gallery 
i get this in the js console:
Uncaught Error: Could not find module `dummy/tests/helpers/data-generator` imported from `dummy/services/dimensional-data-source`
or I am doing something wrong?

**Comment by ming-codes** [comment]
I think this may have to do with the `ember-cli` upgrade a few days ago. I'll need to investigate this further.

Meanwhile, if you need to get things done, you can revert the ember-cli version back to 1.13.8.
