### ISSUE TITLE
hash locationType for demo app

### ISSUE THREAD

**Issue by mike-north** [lightblade/ember-cli-d3#3]
github pages doesn't work properly without using hash navigation. 

https://github.com/lightblade/ember-cli-d3/blob/master/tests/dummy/config/environment.js#L42-L44

In "production", you'll want something like

``` js
ENV.locationType = 'hash';
ENV.baseURL = '/ember-cli-d3';
```

**Comment by ming-codes** [comment]
Thanks! This is fixed now.
