### ISSUE TITLE
NPM error upgrading to 1.1.0+

### ISSUE THREAD

**Issue by wolfbiter** [lightblade/ember-cli-d3#36]
![image](https://cloud.githubusercontent.com/assets/1360563/11770047/d5ab70b8-a1a9-11e5-80d1-647d3709524d.png)

looks like this line `var list = app.options.d3.plugins || {};`

**Comment by wolfbiter** [comment]
what is `app.options.d3`? is it a problem for it to be undefined?

**Comment by ming-codes** [comment]
Duplicate of #33?

**Comment by ming-codes** [comment]
There's no problem for it to be undefined. It looks like a bug in the `index.js` for not using the default options object in L52.
