### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by BryanHunt** [lightblade/ember-cli-d3#51]
FYI, I've been working on ember-d3 as well.  You can see my work here: 

https://github.com/BryanHunt/ember-d3-components
https://github.com/BryanHunt/ember-d3-charts

If you have any interest in collaborating, I'd be open to discussion.

**Comment by ming-codes** [comment]
Sure! How do you like to collaborate?

It seems that `ember-d3-charts` are pre-built charting components. It is not the aim of `ember-cli-d3` to become a component library. Perhaps it can be the lower level components that powers `ember-d3-charts`?

**Comment by BryanHunt** [comment]
ember-d3-charts are pre-build charting components build on top of the low level ember-d3-components library.

**Comment by ming-codes** [comment]
I see.

I've taken a look at your libs. As you may know, there are many other Ember Addons doing similar things. Each one is doing things slightly differently. I'll list out a few that are significant.
- [Netflix/ember-nf-graph](https://github.com/Netflix/ember-nf-graph) - Does composeable graph components.
- [offirgolan/ember-cli-nvd3](https://github.com/offirgolan/ember-cli-nvd3) - Prebuilt charts with NVD3
- [RavelLaw/e3](https://github.com/RavelLaw/e3) - Low level rendering similar to d3, but with no dependency.

It seems your library is very similar to Netflix's nf-graph. Why not contribute there?
