### ISSUE TITLE
Broccoli Plugin: [Funnel] failed

### ISSUE THREAD

**Issue by lllama** [lightblade/ember-cli-d3#58]
The plugin collection is currently failing. The code seems to look for named-amd/main.js in each dir in d3-plugins-dist but these files aren't present, so the build fails.

Is there an install step that I'm missing?

**Comment by lllama** [comment]
Just a quick update - cloning the repo, `npm install && bower install`, followed by `ember serve` gives the same error

```
Error: ENOENT: no such file or directory, symlink 'C:\<SNIP>\documents\development\ember-cli-d3\node_modules\d3-plugins-dist\dist\larskotthoff\chernoff\named-amd\main.js' -> 'C:\<SNIP>documents\development\ember-cli-d3\tmp\funnel-output_path-84y0f6pN.tmp\d3-plugins-dist\larskotthoff\chernoff\named-amd\main.js'
```

**Comment by ming-codes** [comment]
I'll need to investigate this further, but it seems to be a Windows issue.

Meanwhile, can you try cloning the repo and running the tests?

**Comment by ming-codes** [comment]
I can't reproduce the issue. Have you interrupted an `npm install` before? It could be caused by corrupted `node_modules/`.

**Comment by lllama** [comment]
Cloning the repo and running the tests gives the same error. I tried also using the latest release zip file, and got the same error. Cloning on linux and running the tests works ok, plus the demo and guides work with `ember serve`. So it looks like a Windows issue (boo).

Some version info:

Linux 

```
$ ember --version
version: 1.13.13
node: 5.6.0
npm: 2.14.10
os: linux x64

```

Windows

```
[4+]:> ember --version
version: 1.13.13
node: 5.1.0
npm: 2.14.10
os: win32 x64
```

I'll try updating node and see whether that makes a difference. Thank you for the response.

**Comment by lllama** [comment]
Sadly, this looks like a Windows issue. Funnel seems to have trouble creating either the symlinks (running as admin), or the tmp files (running as non-admin), which then causes the crash.

Looks like this has been reported on Funnel: broccolijs/broccoli-funnel/issues/60 (and possibly broccolijs/broccoli-funnel/issues/53)

**Comment by lllama** [comment]
ok - this is definitely related to broccoli-funnel and (more specifically) walk-sync, so I'm going to close this. Apologies for polluting your issue tracker :smile:
