### ISSUE TITLE
help with simple example?

### ISSUE THREAD

**Issue by adhamhf** [lightblade/ember-cli-d3#72]
hi,  I'm a d3 noob and need help just getting started.  I want to get started just with a simple shape like a line or circle, I'm having trouble wrapping my head around that because of my lack of d3 experience.

**Comment by ming-codes** [comment]
Hi @adhamhf,

For people that just starting out with d3, I recommend the [blockbuilder](http://blockbuilder.org). It will let you clone other people's d3 code (what we call blocks), and having live coding set up for you to play with.

For books, I highly recommend [d3 in action](https://www.manning.com/books/d3-js-in-action) by Elijah Meek. The book covers good details and go over the main concepts of d3 pretty well.

Good luck!
