### ISSUE TITLE
registerWaiter breaks ember-app 2.13.0 in production

### ISSUE THREAD

**Issue by badazz91** [lightblade/ember-cli-d3#76]
When running in production mode this here unfortunetly

https://github.com/ming-codes/ember-cli-d3/blob/a571c1b6ce7a89e4a9e3ca3d606d701198585294/vendor/ember-d3-ext/ember-d3-ext.js#L110

breaks the app.

See also [emberjs#15206](https://github.com/emberjs/ember.js/issues/15206)

**Comment by rwjblue** [comment]
Thanks for tracking this down! In general it _should_ be safe here because the runInDebug callback should not be invoked in production builds. 

We should do some testing to confirm that...

**Comment by ming-codes** [comment]
@badazz91 `Ember.runInDebug` is a no-op in production build. Maybe look into why it's being called in there?

**Comment by ming-codes** [comment]
I can confirm it does happens in prod build. Let me see what else I can find.

**Comment by ming-codes** [comment]
@rwjblue Try this. `Ember.runInDebug(console.log.bind(console, 'Hello'))` should not print anything in prod build. It does in `ember-source@2.13`, but not in `ember-source@2.12`.

Just `ember s --environment=production` would do

**Comment by rwjblue** [comment]
Eeeeck! That seems bad! 

We need to open an issue over on emberjs/ember.js specifically about runInDebug being broken in prod builds....

**Comment by rwjblue** [comment]
I created https://github.com/emberjs/ember.js/issues/15212 for tracking.

**Comment by ming-codes** [comment]
Thanks @rwjblue! I'll be closing this one.
